global_frame: odom
rolling_window: true
track_unknown_space: true
cost_scaling_factor: 10.0
inflation_radius: 0.5

inflate_unknown: true

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}