ur3_mainpulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains:
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - wrist_3_joint
    - rh_l1
    - rh_l2
    - rh_p12_rn
    - rh_r2
  gains:
    wrist_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rh_l1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rh_l2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rh_p12_rn:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rh_r2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1